### ISSUE TITLE
Won't open on macOS 10.12.6

### ISSUE THREAD

**Issue by rmlewisuk** [frankdilo/sblack#1]
The website says "Version 1.0.1, macOS 10.12 or later required" but I am unable to open it on 10.12.6

### Steps to reproduce

1. Download the app on macOS 10.12.6
2. Try to open the app

### Expected behaviour
App should open

### Actual behaviour
Warning shown: "You have macOS 10.12.6. The application requires macOS 10.13 or later."

![image](https://user-images.githubusercontent.com/948436/35975391-7ad931aa-0cd4-11e8-90f3-62e91ca2f96b.png)

**Comment by AlexSwensen** [comment]
A great solution would be to upgrade your mac to the latest version of macOS. :-)

**Comment by rmlewisuk** [comment]
> A great solution would be to upgrade your mac to the latest version of macOS

"Upgrade" 😂

**Comment by tenpaiyomi** [comment]
@AlexSwensen as one of the many users who have had issues with High Sierra and had to revert to Sierra, I'd much rather avoid that "upgrade," lol.  I'm not sure of the semantics in the app that would require it to run on 10.13, but I suspect it is probably just a situation of changing the `MACOSX_DEPLOYMENT_TARGET` from 10.13 to 10.12.

@frankdilo possible to get that changed?

**Comment by BecomingCoder** [comment]
I just downloaded this and getting the same issue.  If this shouldn't work on 10.12 then please change the website to reflect that or update the Xcode compile to include 10.12 (more favorable outcome.)

**Comment by frankdilo** [comment]
Guys, I just released a new version that adds macOS 10.12 support. Can you report to me if it works on your system?

**Comment by frankdilo** [comment]
https://github.com/frankdilo/sblack/releases/tag/20180208001

**Comment by tenpaiyomi** [comment]
@frankdilo Worked
